
CREATE DATABASE IF NOT EXISTS zup DEFAULT CHARACTER SET utf8;
USE zup;

DROP TABLE IF EXISTS tb_poi;

CREATE TABLE tb_poi (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  x int(11) DEFAULT NULL,
  y int(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;